In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
a = [1,2,3,4,"hello",4.6]
a

[1, 2, 3, 4, 'hello', 4.6]

In [5]:
np.array(a)

array(['1', '2', '3', '4', 'hello', '4.6'], dtype='<U32')

In [6]:
l = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
l

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [7]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# 1 d  array of zeros
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [5]:
# 2d array or matrix of zeros
arr = np.zeros((4,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [7]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [8]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [12]:
arr = np.linspace(0,1,1000)
arr

array([0.        , 0.001001  , 0.002002  , 0.003003  , 0.004004  ,
       0.00500501, 0.00600601, 0.00700701, 0.00800801, 0.00900901,
       0.01001001, 0.01101101, 0.01201201, 0.01301301, 0.01401401,
       0.01501502, 0.01601602, 0.01701702, 0.01801802, 0.01901902,
       0.02002002, 0.02102102, 0.02202202, 0.02302302, 0.02402402,
       0.02502503, 0.02602603, 0.02702703, 0.02802803, 0.02902903,
       0.03003003, 0.03103103, 0.03203203, 0.03303303, 0.03403403,
       0.03503504, 0.03603604, 0.03703704, 0.03803804, 0.03903904,
       0.04004004, 0.04104104, 0.04204204, 0.04304304, 0.04404404,
       0.04504505, 0.04604605, 0.04704705, 0.04804805, 0.04904905,
       0.05005005, 0.05105105, 0.05205205, 0.05305305, 0.05405405,
       0.05505506, 0.05605606, 0.05705706, 0.05805806, 0.05905906,
       0.06006006, 0.06106106, 0.06206206, 0.06306306, 0.06406406,
       0.06506507, 0.06606607, 0.06706707, 0.06806807, 0.06906907,
       0.07007007, 0.07107107, 0.07207207, 0.07307307, 0.07407

In [13]:
np.random.rand(10)

array([0.47865397, 0.1548486 , 0.0526445 , 0.85178425, 0.53124655,
       0.14741168, 0.07817131, 0.60050864, 0.99920963, 0.62690539])

In [16]:
#Normalized outpput
np.random.rand(10)

array([0.97080173, 0.53008597, 0.45065411, 0.84950749, 0.87397096,
       0.42719162, 0.47970795, 0.79681436, 0.16208207, 0.62470635])

In [17]:
#Standardized Output
np.random.randn(10)

array([ 0.54613055, -0.37489877,  0.4787194 ,  0.65120882, -0.21347458,
       -0.91284076,  0.23671027,  0.76044756,  1.04914083,  0.33505285])

In [18]:
# for single random number generation
np.random.randint(8)

2

In [20]:
# fo rmultiple random numbers between an interval
np.random.randint(8,100,46)

array([39, 14, 80, 69, 11, 43, 21, 43, 28, 61, 67, 94, 82, 16,  8, 60, 69,
       41, 85, 37, 94, 11, 19, 53, 21, 41, 79, 46, 68, 15, 98, 79, 17, 72,
       76, 59, 88, 77, 67, 74, 96, 34, 61,  8, 68, 23], dtype=int32)

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [29]:
#arr.sum is a python function
arr.sum()

np.int64(45)

In [32]:
#Columnwise sum (numpy function)
np.sum(arr,axis=0)


array([12, 15, 18])

In [33]:
#Rowwise sum (numpy function)
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [34]:
arr.mean()

np.float64(5.0)

In [35]:
arr.std()

np.float64(2.581988897471611)

In [39]:
#index of maximum element
arr.argmax()

np.int64(8)

In [38]:
# index of minimum element
arr.argmin()

np.int64(0)

In [40]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
#for cnverting/ reshaping the array into matrix/2-dimensional from vector/1-dimensional
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [48]:
arr = np.arange(11,21)

In [49]:
arr[6]#indexing

np.int64(17)

In [50]:
arr[1:5]#slicing

array([12, 13, 14, 15])

In [51]:
#step slicing
arr[3::2]

array([14, 16, 18, 20])

In [53]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [56]:
# will print ther oth row in the matrix
arr[0]

array([1, 2, 3, 4, 5])

In [57]:
arr[2]#2nd row in the matrix

array([11, 12, 13, 14, 15])

In [58]:
arr[0,0]#prints the particulr element at 0,0 index

np.int64(1)

In [60]:
arr[0:3,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [61]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [66]:
arr = np.arange(11,23)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [67]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [68]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20, 22])

In [69]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [73]:
arr2 =a1+a2
arr2

array([ 7,  9, 11, 13, 15])

In [75]:
arr3 = a1-a2
arr3

array([-5, -5, -5, -5, -5])

In [77]:
arr4 = a1*a2
arr4

array([ 6, 14, 24, 36, 50])

In [79]:
arr5 = a1/a2
arr5

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [80]:
l = [10,20,30,40]
arr = np.array(l)

In [81]:
#Broadcasting
arr +10

array([20, 30, 40, 50])

In [84]:
arrt = np.arange(1,26).reshape(5,5)

In [85]:
arrt *10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [96]:
a = np.arange(1,21)

In [88]:
slice = a[:15]

In [90]:
slice= slice*10
slice

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100,
       1200, 1300, 1400, 1500])

In [95]:
a

array([ 1,  2,  3,  4, 10, 10,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
a[4:6] *10

array([50, 60])

In [98]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [101]:
A

array([[1, 2],
       [3, 4]])

In [102]:
B


array([[5, 6],
       [7, 8]])

In [105]:
A*B # this is not how multip;icaatin works in matrix

array([[ 5, 12],
       [21, 32]])

In [106]:
A @ B # this is how muliplication works in matrix, it is done using @

array([[19, 22],
       [43, 50]])

In [107]:
# or we can do the mtrxi multiplication this wy also
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [108]:
# transpose of matrix
A.T

array([[1, 3],
       [2, 4]])

In [111]:
A

array([[1, 2],
       [3, 4]])

In [112]:
B

array([[5, 6],
       [7, 8]])

In [113]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [115]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [118]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [119]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [124]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [125]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]